# Generated by Django 6.0.6 on 2026-08-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_attendance'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'date'], name='accounts_at_student_c6ff0f_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='accounts_at_status_2da0a5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student', 'month', 'year', 'is_paid'], name='accounts_pa_student_bd7d51_idx'),
        ),
    ]
