# Generated by Django 6.0.6 on 2026-08-17 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_attendance_accounts_at_student_c6ff0f_idx_and_more'),
        ('exams', '0003_alter_exam_exam_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['created_by', '-date'], name='exams_exam_created_a38d70_idx'),
        ),
        migrations.AddIndex(
            model_name='markentry',
            index=models.Index(fields=['subject', 'result'], name='exams_marke_subject_08dfad_idx'),
        ),
    ]
