# Generated by Django 6.0.6 on 2026-08-26 03:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_exam_exams_exam_created_a38d70_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='markentry',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='markentry',
            name='marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
