# Generated by Django 6.0.6 on 2026-09-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_sitesettings_academy_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='academy_name',
            field=models.CharField(default='Kornofuli Biggan Academy', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, default='Kornofuli, Kishoreganj, Bangladesh'),
        ),
    ]
