# Generated by Django 6.0.6 on 2026-09-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_sitesettings_academy_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(default='Kornofuli, Kishoreganj — Premier Coaching Center', max_length=300),
        ),
    ]
