# Generated by Django 6.0.6 on 2026-09-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_sitesettings_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, default='Pakundia, Kishoreganj, Bangladesh'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(default='Pakundia, Kishoreganj — Premier Coaching Center', max_length=300),
        ),
    ]
