# Generated by Django 6.0.6 on 2026-09-17 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_attendance_accounts_at_student_c6ff0f_idx_and_more'),
        ('home', '0006_alter_sitesettings_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='classroom',
            field=models.ForeignKey(blank=True, help_text='Leave empty for a site-wide notice; select a class for class-specific notice.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='accounts.classroom'),
        ),
    ]
